### ISSUE TITLE
how to use private S3 buckets as update source

### ISSUE THREAD

**Issue by truar117** [electron/update-electron-app#146]
Hello,

I publish my App in a private bucket. The reading of this bucket should be restricted by an technical IAM user that has read rights to this bucket. Unfortunately the update-electron-app doesn't support the using of accesskey and access-secret, as provided in the publisher configuration. The access could also be handled by aws4 and passing the request-params, but I doesn't find a solution to pass the request-options to the update-electron-app call? Thank You for any help or hint/solution

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by anaisbetts** [comment]
@truar117 Download the files yourself in your app to a folder (not a temp folder, pick a consistent one or else AV will e mad at you), then instead of passing a URL to the updater, pass the path to the folder instead
