### ISSUE TITLE
Recommended package `electron-installer-zip` wiping entire directories

### ISSUE THREAD

**Issue by rah-ool** [electron/update-electron-app#38]
For macOS, [electron-installer-zip](https://github.com/electron-userland/electron-installer-zip) is recommended to package an `.app` as a `.zip` file, but the project is not actively maintained and has a significant bug that [wipes user's drives](https://github.com/electron-userland/electron-installer-zip/issues/9); use `/` instead of `./` per their documentation and your current working directory will be gone. I recommend instead [electron-builder](https://github.com/electron-userland/electron-builder) or showing users how to zip the requisite files themselves.

**Comment by MarshallOfSound** [comment]
@rah-ool That's not a bug in `electron-installer-zip` rather a misuse.  Most modules (builder, forge and packager included) will overwrite the output directory / output file if it already exists and if that path is defined badly as `/` then it's gonna wipe everything.

There are things modules can do to make this logic safer, E.g. there's no reason `electron-installer-zip` can't just delete the output file instead of the output directory and I've raised [a PR](https://github.com/electron-userland/electron-installer-zip/pull/10) on that module to that effect.

There's nothing on our end to do here though.
